# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
        # Prevent giant files from being committed.
    -   id: check-added-large-files
        # Check for files that contain merge conflict strings.
    -   id: check-merge-conflict
        # Check for debugger imports and py37+ `breakpoint()` calls in python source.
    -   id: debug-statements
        # Don't commit to master branch.
    -   id: no-commit-to-branch

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        types: [file, python]
        args: [--config=./pyproject.toml]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        types: [file, python]
        args: [--config=./.flake8]
