language: minimal
dist: xenial

env:
  matrix:
    - PYTHON_VERSION="36"
    - PYTHON_VERSION="37"
    - PYTHON_VERSION="38" TEST_BLACK=true

install:
  # Install miniconda
  # -----------------
  - echo "Installing miniconda"
  - export CONDA_BASE="http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
  - wget --quiet "${CONDA_BASE}" -O miniconda.sh;
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:$PATH"

  # Configure conda
  # ---------------
  - echo "Configure conda"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda config --add channels conda-forge
  - conda update --quiet conda
  - ENV_NAME="tephi-dev"
  - conda env create --quiet --file="ci/requirements/py3/py${PYTHON_VERSION}.yml"
  - source activate ${ENV_NAME}

  # Output debug info
  # -----------------
  - conda list -n ${ENV_NAME}
  - conda list -n ${ENV_NAME} --explicit
  - conda info -a

  # Build the package
  # -----------------
  - pip install -e .

script:
  - export INSTALL_DIR=$(pwd)

  - >
    if [[ "${TEST_BLACK}" == "true" ]]; then
      echo $(black --version);
      rm ${INSTALL_DIR}/.gitignore;
      black --check ${INSTALL_DIR};
    fi

  - pytest --cov 

after_success: coveralls
