name: Test tephi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        key: tox
        path: |
          .tox

    - name: Install tox
      run: pip3 install --user tox

    - name: Run tox
      run: tox