name: Test tephi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        key: tox-${{ hashFiles('ci/requirements/dev.yml') }}-${{ hashFiles('tox.ini') }}
        path: |
          .tox

    - name: Install tox
      run: pip3 install --user tox

    - name: Run tox
      run: tox